from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path

from .config import ToolConfig
from .config_io import load_tool_config
from .detect import detect_repo
from .io_utils import read_json, read_text
from .normalize import normalize_markdown
from .patch_engine import write_or_diff
from .result_types import FileResult


@dataclass(frozen=True)
class OkfConceptSpec:
    rel_path: Path
    type_name: str
    title: str
    description: str
    tags: tuple[str, ...]
    canonical: str
    body: str
    resource: str = ""
    status: str = "active"
    source: str = "agentsgen"
    kind: str = ""


def _yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _render_frontmatter(spec: OkfConceptSpec) -> str:
    lines = [
        "---",
        f"type: {_yaml_quote(spec.type_name)}",
        f"title: {_yaml_quote(spec.title)}",
        f"description: {_yaml_quote(spec.description)}",
        "tags:",
    ]
    for tag in spec.tags:
        lines.append(f"  - {_yaml_quote(tag)}")
    lines.append(f"canonical: {_yaml_quote(spec.canonical)}")
    lines.append(f"source: {_yaml_quote(spec.source)}")
    lines.append(f"status: {_yaml_quote(spec.status)}")
    if spec.kind:
        lines.append(f"kind: {_yaml_quote(spec.kind)}")
    if spec.resource:
        lines.append(f"resource: {_yaml_quote(spec.resource)}")
    lines.extend(["---", ""])
    return "\n".join(lines)


def _render_concept(spec: OkfConceptSpec) -> str:
    body = spec.body.strip()
    return normalize_markdown(_render_frontmatter(spec) + body + "\n")


def _render_root_index(
    repo_entries: list[tuple[str, str]], assets_entries: list[tuple[str, str]]
) -> str:
    lines = [
        """---
okf_version: "0.1"
title: "ABVX OKF Bundle"
description: "Portable repo knowledge bundle generated by agentsgen."
source: "agentsgen"
status: "active"
---
""".strip(),
        "",
        "# ABVX OKF Bundle",
        "",
    ]
    if repo_entries:
        lines.extend(["## Repo", ""])
        for rel, desc in repo_entries:
            name = Path(rel).stem.replace("-", " ").title()
            lines.append(f"* [{name}](repo/{rel}) - {desc}")
        lines.append("")
    if assets_entries:
        lines.extend(["## Assets", ""])
        for rel, desc in assets_entries:
            name = Path(rel).stem.replace("-", " ").title()
            lines.append(f"* [{name}](assets/{rel}) - {desc}")
        lines.append("")
    return normalize_markdown("\n".join(lines))


def _render_index(title: str, entries: list[tuple[str, str]]) -> str:
    lines = [f"# {title}", ""]
    for rel, desc in entries:
        name = Path(rel).stem.replace("-", " ").title()
        lines.append(f"* [{name}]({rel}) - {desc}")
    lines.append("")
    return normalize_markdown("\n".join(lines))


def _repo_overview_body(target: Path, cfg: ToolConfig, source_dir: Path) -> str:
    stack = (
        str((cfg.project or {}).get("primary_stack", "")).strip()
        or str(cfg.project_info.stack or "").strip()
    )
    commands = cfg.commands or {}
    docs = [
        "architecture.md",
        "how-to-run.md",
        "how-to-test.md",
        "data-contracts.md",
    ]
    available_docs = [name for name in docs if (source_dir / name).is_file()]
    lines = [
        "# Summary",
        f"Primary stack: `{stack or 'unknown'}`.",
        "",
        "# Exported sources",
    ]
    for name in available_docs:
        target_rel = {
            "architecture.md": "/repo/architecture.md",
            "how-to-run.md": "/repo/runbook.md",
            "how-to-test.md": "/repo/test-flow.md",
            "data-contracts.md": "/repo/contracts.md",
        }[name]
        lines.append(f"* [{name}]({target_rel})")
    lines.extend(["", "# Commands"])
    for key in ("install", "dev", "test", "lint", "build", "format"):
        value = str(commands.get(key, "")).strip()
        if value:
            lines.append(f"* `{key}`: `{value}`")
    lines.extend(
        [
            "",
            "# Links",
            "* [Command Surface](/assets/entrypoints.md)",
            f"* Repo root: `{target.resolve()}`",
        ]
    )
    return "\n".join(lines)


def _entrypoints_body(target: Path) -> str:
    manifest_path = target / "agents.entrypoints.json"
    if not manifest_path.is_file():
        return (
            "# Summary\n"
            "No `agents.entrypoints.json` file was found at export time.\n"
        )

    payload = read_json(manifest_path)
    commands = payload.get("commands", [])
    lines = [
        "# Summary",
        "Rendered from `agents.entrypoints.json`.",
        "",
        "# Commands",
    ]
    if not commands:
        lines.append("No commands were declared.")
    else:
        lines.extend(
            [
                "| ID | Title | Command | Source | |",
                "| --- | --- | --- | --- |",
            ]
        )
        for row in commands:
            source = row.get("source") or {}
            source_kind = str(source.get("kind", "")).strip() or "unknown"
            lines.append(
                "| "
                f"`{row.get('id', '')}` | "
                f"{row.get('title', '')} | "
                f"`{row.get('command', '')}` | "
                f"{source_kind} |"
            )
    lines.extend(
        [
            "",
            "# Citations",
            "* [Repo entrypoints manifest](../agents.entrypoints.json)",
        ]
    )
    return "\n".join(lines)


def _source_concepts(target: Path, source_dir: Path) -> list[OkfConceptSpec]:
    cfg = (
        load_tool_config(target)
        if (target / ".agentsgen.json").exists()
        else ToolConfig.from_detect(detect_repo(target))
    )
    mapping = [
        (
            source_dir / "architecture.md",
            Path("repo/architecture.md"),
            "Repo Guide",
            "Architecture Overview",
            "High-level structure, boundaries, and important modules.",
            ("repo", "architecture"),
            "architecture",
        ),
        (
            source_dir / "how-to-run.md",
            Path("repo/runbook.md"),
            "Workflow",
            "Runbook",
            "Practical run and development commands for the repository.",
            ("repo", "workflow", "runbook"),
            "runbook",
        ),
        (
            source_dir / "how-to-test.md",
            Path("repo/test-flow.md"),
            "Workflow",
            "Test Flow",
            "Test, lint, verification, and fast/full loop guidance.",
            ("repo", "workflow", "testing"),
            "test-flow",
        ),
        (
            source_dir / "data-contracts.md",
            Path("repo/contracts.md"),
            "Data Contract",
            "Data Contracts",
            "Compatibility, invariants, and change-safety guidance.",
            ("repo", "contracts", "compatibility"),
            "contracts",
        ),
    ]

    concepts: list[OkfConceptSpec] = [
        OkfConceptSpec(
            rel_path=Path("repo/overview.md"),
            type_name="Repo Overview",
            title="Repository Overview",
            description="Generated summary of the repo context and exported knowledge surfaces.",
            tags=("repo", "overview", "generated"),
            canonical=".agentsgen.json",
            body=_repo_overview_body(target, cfg, source_dir),
            kind="overview",
        )
    ]

    for source_path, rel_path, type_name, title, description, tags, kind in mapping:
        if not source_path.is_file():
            continue
        concepts.append(
            OkfConceptSpec(
                rel_path=rel_path,
                type_name=type_name,
                title=title,
                description=description,
                tags=tags,
                canonical=str(source_path.relative_to(target)).replace("\\", "/"),
                body=read_text(source_path),
                kind=kind,
            )
        )

    concepts.append(
        OkfConceptSpec(
            rel_path=Path("assets/entrypoints.md"),
            type_name="Command Surface",
            title="Command Surface",
            description="Machine-readable repo commands rendered as a human- and agent-readable concept.",
            tags=("repo", "commands", "entrypoints"),
            canonical="agents.entrypoints.json",
            body=_entrypoints_body(target),
            kind="entrypoints",
            resource="agents.entrypoints.json",
        )
    )
    return concepts


def export_okf_bundle(
    target: Path,
    *,
    source_dir: Path,
    output_dir: Path,
    dry_run: bool,
    print_diff: bool,
) -> list[FileResult]:
    results: list[FileResult] = []
    concepts = _source_concepts(target, source_dir)

    repo_entries: list[tuple[str, str]] = []
    assets_entries: list[tuple[str, str]] = []
    payloads: list[tuple[Path, str]] = []

    for concept in concepts:
        payloads.append((output_dir / concept.rel_path, _render_concept(concept)))
        entry = (
            concept.rel_path.name,
            concept.description,
        )
        if concept.rel_path.parts[0] == "repo":
            repo_entries.append(entry)
        elif concept.rel_path.parts[0] == "assets":
            assets_entries.append(entry)

    payloads.insert(
        0, (output_dir / "index.md", _render_root_index(repo_entries, assets_entries))
    )
    payloads.append(
        (output_dir / "repo" / "index.md", _render_index("Repo", repo_entries))
    )
    payloads.append(
        (output_dir / "assets" / "index.md", _render_index("Assets", assets_entries))
    )

    for path, content in payloads:
        changed, diff = write_or_diff(path, content, dry_run, print_diff)
        action = "created"
        message = "created OKF file"
        if path.exists() and not changed:
            action = "skipped"
            message = "already up to date"
        elif path.exists() and changed:
            action = "updated"
            message = "updated OKF file"
        results.append(
            FileResult(
                path=path,
                action=action,
                message=message,
                changed=changed,
                diff=diff,
            )
        )

    return results


def okf_results_payload(results: list[FileResult]) -> list[dict[str, object]]:
    return [
        {
            "path": str(row.path),
            "action": row.action,
            "message": row.message,
            "changed": bool(row.changed),
            "diff": row.diff or "",
        }
        for row in results
    ]
