from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .actions import FileResult, _handle_file, _handle_generated_json_file

_TASK_ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
_CONTRACT_SECTION = "task_contract"
_DEFAULT_ACCEPTANCE = (
    "Implementation matches the requested scope.",
    "Relevant checks ran or are explicitly documented.",
    "Diff remains minimal and reviewable.",
)
_PASSED_CHECK_STATUSES = {"pass", "passed", "ok", "success", "succeeded"}
_FAILED_CHECK_STATUSES = {"fail", "failed", "error", "errored"}
_PENDING_CHECK_STATUSES = {
    "pending",
    "scheduled",
    "queued",
    "skipped",
    "not-run",
    "needs-review",
}
_BLOCKING_SEVERITIES = {"low", "medium", "high"}


def _utc_now_iso() -> str:
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def _stable_payload_without_timestamp(payload: dict[str, object]) -> str:
    clone = json.loads(json.dumps(payload))
    clone["generated_at"] = ""
    return json.dumps(clone, sort_keys=True, separators=(",", ":"))


def normalize_task_id(task_id: str) -> str:
    value = (task_id or "").strip().lower()
    if not _TASK_ID_RE.fullmatch(value):
        raise ValueError(
            "task_id must match ^[a-z0-9][a-z0-9._-]*$ and stay filesystem-safe."
        )
    return value


def task_dir(root: Path, task_id: str) -> Path:
    return root / "docs" / "ai" / "tasks" / normalize_task_id(task_id)


def build_contract_markdown(
    *,
    task_id: str,
    title: str,
    summary: str,
    acceptance: list[str],
) -> str:
    acceptance_rows = acceptance or list(_DEFAULT_ACCEPTANCE)
    bullets = "\n".join(f"- {item}" for item in acceptance_rows)
    body = "\n".join(
        [
            f"# Task Contract: {title}",
            "",
            f"- **Task ID:** `{task_id}`",
            "- **Generated by:** `agentsgen`",
            "",
            "## Summary",
            summary.strip() or "Task contract captured by agentsgen.",
            "",
            "## Acceptance Criteria",
            bullets,
        ]
    ).strip()
    return "\n".join(
        [
            f"<!-- AGENTSGEN:START section={_CONTRACT_SECTION} -->",
            body,
            f"<!-- AGENTSGEN:END section={_CONTRACT_SECTION} -->",
            "",
        ]
    )


def apply_task_init(
    root: Path,
    *,
    task_id: str,
    title: str | None,
    summary: str,
    acceptance: list[str],
    output_path: Path,
    dry_run: bool = False,
) -> tuple[list[FileResult], dict[str, object]]:
    normalized_task_id = normalize_task_id(task_id)
    title_value = (
        title or normalized_task_id.replace("-", " ").replace("_", " ")
    ).strip()
    title_value = (
        title_value[:1].upper() + title_value[1:] if title_value else normalized_task_id
    )
    acceptance_rows = [item.strip() for item in acceptance if item.strip()]
    if not acceptance_rows:
        acceptance_rows = list(_DEFAULT_ACCEPTANCE)

    payload = {
        "version": 1,
        "generated_by": "agentsgen",
        "generated_at": _utc_now_iso(),
        "task_id": normalized_task_id,
        "title": title_value,
        "summary": summary.strip() or "Task contract captured by agentsgen.",
        "acceptance": acceptance_rows,
        "path": str(output_path.relative_to(root)).replace("\\", "/"),
    }
    result = _handle_file(
        output_path,
        build_contract_markdown(
            task_id=normalized_task_id,
            title=title_value,
            summary=payload["summary"],
            acceptance=acceptance_rows,
        ),
        required=[_CONTRACT_SECTION],
        dry_run=dry_run,
        print_diff=False,
    )
    return [result], payload


def _git_changed_files(root: Path) -> list[str]:
    if not (root / ".git").exists():
        return []
    try:
        proc = subprocess.run(
            ["git", "-C", str(root), "status", "--short", "--untracked-files=all"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return []
    if proc.returncode != 0:
        return []
    rows: set[str] = set()
    for line in proc.stdout.splitlines():
        if len(line) < 4:
            continue
        raw = line[3:].strip()
        if " -> " in raw:
            raw = raw.split(" -> ", 1)[1].strip()
        if raw:
            rows.add(raw.replace("\\", "/"))
    return sorted(rows)


def _preserve_generated_timestamp(
    payload: dict[str, object], output_path: Path
) -> dict[str, object]:
    if not output_path.exists():
        return payload
    try:
        existing = json.loads(output_path.read_text(encoding="utf-8"))
    except Exception:
        return payload
    if not (
        isinstance(existing, dict)
        and str(existing.get("generated_by", "")) == "agentsgen"
        and _stable_payload_without_timestamp(existing)
        == _stable_payload_without_timestamp(payload)
    ):
        return payload
    clone = dict(payload)
    clone["generated_at"] = str(existing.get("generated_at", "") or "")
    return clone


def _normalize_check_status(status: str) -> str:
    value = (status or "").strip().lower()
    if value in _PASSED_CHECK_STATUSES:
        return "passed"
    if value in _FAILED_CHECK_STATUSES:
        return "failed"
    if value in _PENDING_CHECK_STATUSES:
        return "pending"
    return value or "recorded"


def _parse_check_rows(checks: list[str]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for item in checks:
        raw = item.strip()
        if not raw:
            continue
        if "=" in raw:
            name, status = raw.split("=", 1)
        elif ":" in raw:
            name, status = raw.split(":", 1)
        else:
            name, status = raw, "recorded"
        status_value = _normalize_check_status(status)
        rows.append(
            {
                "name": name.strip(),
                "status": status_value,
                "required": True,
                "kind": "check",
            }
        )
    return rows


def _summarize_checks(check_rows: list[dict[str, object]]) -> dict[str, int]:
    summary = {
        "total": len(check_rows),
        "passed": 0,
        "failed": 0,
        "pending": 0,
        "recorded": 0,
    }
    for row in check_rows:
        status = str(row.get("status", "recorded"))
        if status == "passed":
            summary["passed"] += 1
        elif status == "failed":
            summary["failed"] += 1
        elif status == "pending":
            summary["pending"] += 1
        else:
            summary["recorded"] += 1
    return summary


def _artifact_kind(path_value: str) -> str:
    if path_value.endswith(".json"):
        return "json"
    if path_value.endswith(".md"):
        return "markdown"
    if path_value.endswith(".txt"):
        return "text"
    return "file"


def _artifact_details(root: Path, artifacts: list[str]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for item in sorted({value.strip() for value in artifacts if value.strip()}):
        artifact_path = root / item
        rows.append(
            {
                "path": item,
                "kind": _artifact_kind(item),
                "present": artifact_path.exists(),
            }
        )
    return rows


def _summarize_artifacts(
    artifact_details: list[dict[str, object]],
) -> dict[str, int]:
    present = sum(1 for item in artifact_details if item.get("present"))
    total = len(artifact_details)
    return {
        "total": total,
        "present": present,
        "missing": total - present,
    }


def _evidence_status(
    check_summary: dict[str, int],
    artifact_summary: dict[str, int],
) -> str:
    if check_summary["failed"] > 0:
        return "failed"
    if check_summary["pending"] > 0 or artifact_summary["missing"] > 0:
        return "incomplete"
    return "complete"


def _load_task_json(path: Path) -> dict[str, object] | None:
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return payload if isinstance(payload, dict) else None


def _parse_blocking_items(
    status: str, blocking_items: list[str]
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    default_severity = "high" if status == "fail" else "medium"
    for item in blocking_items:
        raw = item.strip()
        if not raw:
            continue
        severity = default_severity
        message = raw
        if ":" in raw:
            maybe_severity, rest = raw.split(":", 1)
            if maybe_severity.strip().lower() in _BLOCKING_SEVERITIES:
                severity = maybe_severity.strip().lower()
                message = rest.strip()
        rows.append(
            {
                "message": message,
                "severity": severity,
                "blocks_apply": True,
            }
        )
    return rows


def _recommendation_for_verdict(
    *, status: str, evidence_status: str, blocking_details: list[dict[str, object]]
) -> str:
    if status == "pass":
        return "Ready to mark complete and merge once final human review is done."
    if status == "fail":
        return "Fix the blocking items before continuing the task."
    if blocking_details:
        return "Resolve blockers, refresh evidence, then re-run verdict."
    if evidence_status == "incomplete":
        return (
            "Run or record the missing checks and artifacts, then refresh the verdict."
        )
    if evidence_status == "failed":
        return "Fix failing checks before advancing this task."
    return "Review the captured evidence bundle before marking the task as pass."


def apply_task_evidence(
    root: Path,
    *,
    task_id: str,
    checks: list[str],
    artifacts: list[str],
    notes: list[str],
    output_path: Path,
    dry_run: bool = False,
) -> tuple[list[FileResult], dict[str, object]]:
    normalized_task_id = normalize_task_id(task_id)
    check_rows = _parse_check_rows(checks)
    artifact_rows = sorted({item.strip() for item in artifacts if item.strip()})
    artifact_details = _artifact_details(root, artifact_rows)
    check_summary = _summarize_checks(check_rows)
    artifact_summary = _summarize_artifacts(artifact_details)
    contract_path = task_dir(root, normalized_task_id) / "contract.md"
    changed_files = _git_changed_files(root)

    payload = {
        "version": 2,
        "generated_by": "agentsgen",
        "generated_at": _utc_now_iso(),
        "task_id": normalized_task_id,
        "checks": check_rows,
        "check_summary": check_summary,
        "changed_files": changed_files,
        "changed_files_count": len(changed_files),
        "artifacts": artifact_rows,
        "artifact_details": artifact_details,
        "artifact_summary": artifact_summary,
        "contract_present": contract_path.exists(),
        "evidence_status": _evidence_status(check_summary, artifact_summary),
        "repo_state": {
            "git_available": (root / ".git").exists(),
            "working_tree_dirty": bool(changed_files),
        },
        "notes": [item.strip() for item in notes if item.strip()],
    }
    payload = _preserve_generated_timestamp(payload, output_path)
    result = _handle_generated_json_file(
        output_path,
        json.dumps(payload, indent=2) + "\n",
        dry_run=dry_run,
        print_diff=False,
    )
    return [result], payload


def apply_task_verdict(
    root: Path,
    *,
    task_id: str,
    status: str,
    summary: str,
    blocking_items: list[str],
    output_path: Path,
    dry_run: bool = False,
) -> tuple[list[FileResult], dict[str, object]]:
    normalized_task_id = normalize_task_id(task_id)
    status_value = (status or "").strip().lower()
    if status_value not in {"pass", "fail", "needs-review"}:
        raise ValueError("status must be one of: pass, fail, needs-review")
    evidence_path = task_dir(root, normalized_task_id) / "evidence.json"
    evidence_generated_path = (
        task_dir(root, normalized_task_id) / "evidence.generated.json"
    )
    evidence_payload = _load_task_json(evidence_path) or _load_task_json(
        evidence_generated_path
    )
    check_summary = (
        dict(evidence_payload.get("check_summary", {}))
        if isinstance(evidence_payload, dict)
        and isinstance(evidence_payload.get("check_summary"), dict)
        else {}
    )
    artifact_summary = (
        dict(evidence_payload.get("artifact_summary", {}))
        if isinstance(evidence_payload, dict)
        and isinstance(evidence_payload.get("artifact_summary"), dict)
        else {}
    )
    evidence_status = (
        str(evidence_payload.get("evidence_status", "unknown"))
        if isinstance(evidence_payload, dict)
        else "unknown"
    )
    blocking_details = _parse_blocking_items(status_value, blocking_items)
    review_ready = (
        status_value == "needs-review"
        and not blocking_details
        and evidence_status == "complete"
    )
    ready_for_apply = (
        status_value == "pass"
        and not blocking_details
        and evidence_status == "complete"
    )
    if status_value == "fail":
        decision = "failed"
    elif ready_for_apply:
        decision = "approved"
    elif review_ready:
        decision = "review-ready"
    else:
        decision = "blocked"

    payload = {
        "version": 2,
        "generated_by": "agentsgen",
        "generated_at": _utc_now_iso(),
        "task_id": normalized_task_id,
        "status": status_value,
        "summary": summary.strip() or "No verdict summary provided.",
        "blocking_items": [item.strip() for item in blocking_items if item.strip()],
        "blocking_details": blocking_details,
        "evidence_status": evidence_status,
        "check_summary": check_summary,
        "artifact_summary": artifact_summary,
        "review_ready": review_ready,
        "ready_for_apply": ready_for_apply,
        "decision": decision,
        "recommendation": _recommendation_for_verdict(
            status=status_value,
            evidence_status=evidence_status,
            blocking_details=blocking_details,
        ),
    }
    payload = _preserve_generated_timestamp(payload, output_path)
    result = _handle_generated_json_file(
        output_path,
        json.dumps(payload, indent=2) + "\n",
        dry_run=dry_run,
        print_diff=False,
    )
    return [result], payload
