from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .actions import FileResult, _handle_file, _handle_generated_json_file

_TASK_ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
_CONTRACT_SECTION = "task_contract"
_DEFAULT_ACCEPTANCE = (
    "Implementation matches the requested scope.",
    "Relevant checks ran or are explicitly documented.",
    "Diff remains minimal and reviewable.",
)


def _utc_now_iso() -> str:
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def _stable_payload_without_timestamp(payload: dict[str, object]) -> str:
    clone = json.loads(json.dumps(payload))
    clone["generated_at"] = ""
    return json.dumps(clone, sort_keys=True, separators=(",", ":"))


def normalize_task_id(task_id: str) -> str:
    value = (task_id or "").strip().lower()
    if not _TASK_ID_RE.fullmatch(value):
        raise ValueError(
            "task_id must match ^[a-z0-9][a-z0-9._-]*$ and stay filesystem-safe."
        )
    return value


def task_dir(root: Path, task_id: str) -> Path:
    return root / "docs" / "ai" / "tasks" / normalize_task_id(task_id)


def build_contract_markdown(
    *,
    task_id: str,
    title: str,
    summary: str,
    acceptance: list[str],
) -> str:
    acceptance_rows = acceptance or list(_DEFAULT_ACCEPTANCE)
    bullets = "\n".join(f"- {item}" for item in acceptance_rows)
    body = "\n".join(
        [
            f"# Task Contract: {title}",
            "",
            f"- **Task ID:** `{task_id}`",
            "- **Generated by:** `agentsgen`",
            "",
            "## Summary",
            summary.strip() or "Task contract captured by agentsgen.",
            "",
            "## Acceptance Criteria",
            bullets,
        ]
    ).strip()
    return "\n".join(
        [
            f"<!-- AGENTSGEN:START section={_CONTRACT_SECTION} -->",
            body,
            f"<!-- AGENTSGEN:END section={_CONTRACT_SECTION} -->",
            "",
        ]
    )


def apply_task_init(
    root: Path,
    *,
    task_id: str,
    title: str | None,
    summary: str,
    acceptance: list[str],
    output_path: Path,
    dry_run: bool = False,
) -> tuple[list[FileResult], dict[str, object]]:
    normalized_task_id = normalize_task_id(task_id)
    title_value = (
        title or normalized_task_id.replace("-", " ").replace("_", " ")
    ).strip()
    title_value = (
        title_value[:1].upper() + title_value[1:] if title_value else normalized_task_id
    )
    acceptance_rows = [item.strip() for item in acceptance if item.strip()]
    if not acceptance_rows:
        acceptance_rows = list(_DEFAULT_ACCEPTANCE)

    payload = {
        "version": 1,
        "generated_by": "agentsgen",
        "generated_at": _utc_now_iso(),
        "task_id": normalized_task_id,
        "title": title_value,
        "summary": summary.strip() or "Task contract captured by agentsgen.",
        "acceptance": acceptance_rows,
        "path": str(output_path.relative_to(root)).replace("\\", "/"),
    }
    result = _handle_file(
        output_path,
        build_contract_markdown(
            task_id=normalized_task_id,
            title=title_value,
            summary=payload["summary"],
            acceptance=acceptance_rows,
        ),
        required=[_CONTRACT_SECTION],
        dry_run=dry_run,
        print_diff=False,
    )
    return [result], payload


def _git_changed_files(root: Path) -> list[str]:
    if not (root / ".git").exists():
        return []
    try:
        proc = subprocess.run(
            ["git", "-C", str(root), "status", "--short", "--untracked-files=all"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return []
    if proc.returncode != 0:
        return []
    rows: set[str] = set()
    for line in proc.stdout.splitlines():
        if len(line) < 4:
            continue
        raw = line[3:].strip()
        if " -> " in raw:
            raw = raw.split(" -> ", 1)[1].strip()
        if raw:
            rows.add(raw.replace("\\", "/"))
    return sorted(rows)


def _preserve_generated_timestamp(
    payload: dict[str, object], output_path: Path
) -> dict[str, object]:
    if not output_path.exists():
        return payload
    try:
        existing = json.loads(output_path.read_text(encoding="utf-8"))
    except Exception:
        return payload
    if not (
        isinstance(existing, dict)
        and str(existing.get("generated_by", "")) == "agentsgen"
        and _stable_payload_without_timestamp(existing)
        == _stable_payload_without_timestamp(payload)
    ):
        return payload
    clone = dict(payload)
    clone["generated_at"] = str(existing.get("generated_at", "") or "")
    return clone


def apply_task_evidence(
    root: Path,
    *,
    task_id: str,
    checks: list[str],
    artifacts: list[str],
    notes: list[str],
    output_path: Path,
    dry_run: bool = False,
) -> tuple[list[FileResult], dict[str, object]]:
    normalized_task_id = normalize_task_id(task_id)
    check_rows = []
    for item in checks:
        raw = item.strip()
        if not raw:
            continue
        if "=" in raw:
            name, status = raw.split("=", 1)
        elif ":" in raw:
            name, status = raw.split(":", 1)
        else:
            name, status = raw, "recorded"
        check_rows.append(
            {"name": name.strip(), "status": status.strip() or "recorded"}
        )

    payload = {
        "version": 1,
        "generated_by": "agentsgen",
        "generated_at": _utc_now_iso(),
        "task_id": normalized_task_id,
        "checks": check_rows,
        "changed_files": _git_changed_files(root),
        "artifacts": sorted({item.strip() for item in artifacts if item.strip()}),
        "notes": [item.strip() for item in notes if item.strip()],
    }
    payload = _preserve_generated_timestamp(payload, output_path)
    result = _handle_generated_json_file(
        output_path,
        json.dumps(payload, indent=2) + "\n",
        dry_run=dry_run,
        print_diff=False,
    )
    return [result], payload


def apply_task_verdict(
    root: Path,
    *,
    task_id: str,
    status: str,
    summary: str,
    blocking_items: list[str],
    output_path: Path,
    dry_run: bool = False,
) -> tuple[list[FileResult], dict[str, object]]:
    del root
    normalized_task_id = normalize_task_id(task_id)
    status_value = (status or "").strip().lower()
    if status_value not in {"pass", "fail", "needs-review"}:
        raise ValueError("status must be one of: pass, fail, needs-review")

    payload = {
        "version": 1,
        "generated_by": "agentsgen",
        "generated_at": _utc_now_iso(),
        "task_id": normalized_task_id,
        "status": status_value,
        "summary": summary.strip() or "No verdict summary provided.",
        "blocking_items": [item.strip() for item in blocking_items if item.strip()],
    }
    payload = _preserve_generated_timestamp(payload, output_path)
    result = _handle_generated_json_file(
        output_path,
        json.dumps(payload, indent=2) + "\n",
        dry_run=dry_run,
        print_diff=False,
    )
    return [result], payload
